name: Update News Index

on:
  push:
    paths:
      - "news/**.md"

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure index.json exists
        run: |
          mkdir -p news
          if [ ! -f news/index.json ]; then
            echo "[]" > news/index.json
          fi

      - name: Get changed files
        id: changes
        uses: actions/github-script@v7
        with:
          script: |
            const files = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: context.payload.before,
              head: context.sha
            });
            const addedOrModified = files.data.files
              .filter(f => f.status === 'added' || f.status === 'modified')
              .map(f => f.filename)
              .filter(name => name.startsWith("news/") && name.endsWith(".md"));
            const deleted = files.data.files
              .filter(f => f.status === 'removed')
              .map(f => f.filename)
              .filter(name => name.startsWith("news/") && name.endsWith(".md"));
            core.setOutput("added_or_modified", addedOrModified.join(" "));
            core.setOutput("deleted", deleted.join(" "));


      - name: Handle deletions
        if: ${{ steps.changes.outputs.deleted != '' }}
        run: |
          for file in ${{ steps.changes.outputs.deleted }}; do
            filename=$(basename "$file")
            jq --arg file "$filename" 'map(select(.file != $file))' news/index.json > tmp.json && mv tmp.json news/index.json
          done

      - name: Handle additions/updates
        if: ${{ steps.changes.outputs.added_or_modified != '' }}
        run: |
          for file in ${{ steps.changes.outputs.added_or_modified }}; do
            filename=$(basename "$file")
            created=$(git log --diff-filter=A --follow --format=%aI -- "$file" | tail -1)
            updated=$(git log -1 --format=%aI -- "$file")
            title=$(head -n 1 "$file" | sed 's/^# *//')
            # 一旦削除してから再追加(更新対応)
            jq --arg file "$filename" 'map(select(.file != $file))' news/index.json > tmp.json && mv tmp.json news/index.json
            jq --arg title "$title" \
               --arg file "$filename" \
               --arg created "$created" \
               --arg updated "$updated" \
               '. += [{"title":$title,"file":$file,"createdAt":$created,"updatedAt":$updated}]' \
               news/index.json > tmp.json && mv tmp.json news/index.json
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add news/index.json
          git commit -m "Update news index" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
